### ISSUE TITLE
add `__array__` method

### ISSUE THREAD

**Issue by nestordemeure** [tskisner/pshmem#13]
`MPIShared` objects can be implicitely casted to Numpy arrays (JAX, for example, will do it). However that conversion is extremely costly (I suspect it either uses the iterator method or explicitely converts it one cell at a type).

Adding an `__array__` method to `MPIShared` would remove this performance footgun for a minimal price:

```python
    def __array__(self):
        """
        Method to convert a MPIShared object into a Numpy array.
        Naive convertion without that method incurs a very large overhead.
        """
        return self.data
```

Do you recommend submitting a PR to add the method or leaving things as is as this might not be triggered often?

**Comment by tskisner** [comment]
This is a good point.  The `data` member is a numpy view of the underlying memory, but apparently just defining `__iter__` will cause numpy functions to access one element at a time.  I will add that and try to think of a unit test.
